class AssistantStatus:

    IDLE = "IDLE"

    ACTIVATED = "ACTIVATED"

    LISTENING = "LISTENING"

    CONFIRMING = "CONFIRMING"

    THINKING = "THINKING"

    SPEAKING = "SPEAKING"

    PROCESSING_PDF = "PROCESSING_PDF"

    ERROR = "ERROR"